"""Description of changes

Revision ID: 391dba40e7e5
Revises: 
Create Date: 2025-04-10 03:01:52.902307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391dba40e7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('address')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
