"""Make doctor_id nullable in appointments

Revision ID: 732cc5fb3910
Revises: 96b9c0b6586d
Create Date: 2025-04-10 13:48:26.392247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732cc5fb3910'
down_revision = '96b9c0b6586d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
