"""Make doctor_id nullable in appointments

Revision ID: 96b9c0b6586d
Revises: 9171362e9839
Create Date: 2025-04-10 04:13:07.261327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b9c0b6586d'
down_revision = '9171362e9839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('doctor_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
